//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inixe.CoinManagement.CoinMarketCap.Api.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inixe.CoinManagement.CoinMarketCap.Api.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: &quot;bitcoin&quot;, 
        ///        &quot;name&quot;: &quot;Bitcoin&quot;, 
        ///        &quot;symbol&quot;: &quot;BTC&quot;, 
        ///        &quot;rank&quot;: &quot;1&quot;, 
        ///        &quot;price_usd&quot;: &quot;4022.6&quot;, 
        ///        &quot;price_btc&quot;: &quot;1.0&quot;, 
        ///        &quot;24h_volume_usd&quot;: &quot;1500750000.0&quot;, 
        ///        &quot;market_cap_usd&quot;: &quot;66677310255.0&quot;, 
        ///        &quot;available_supply&quot;: &quot;16575675.0&quot;, 
        ///        &quot;total_supply&quot;: &quot;16575675.0&quot;, 
        ///        &quot;percent_change_1h&quot;: &quot;0.69&quot;, 
        ///        &quot;percent_change_24h&quot;: &quot;1.14&quot;, 
        ///        &quot;percent_change_7d&quot;: &quot;-3.82&quot;, 
        ///        &quot;last_updated&quot;: &quot;1505843367&quot;, 
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoinMarketCap_Sample {
            get {
                return ResourceManager.GetString("CoinMarketCap_Sample", resourceCulture);
            }
        }
    }
}
